### ISSUE TITLE
Add Schematics and... 

### ISSUE THREAD

**Issue by RAWJUNGLE** [miotislucifugis/Norns-Fates-on-RPi-Cheat-Sheet#1]
HI. 
Add Schematics, and  add .img disk image with the specified settings or make the setup easier, with some kind of script or something else. it would be cool 
Maybe add support Ili9341 displays or DSI display by waveshare https://www.waveshare.com/wiki/5inch_DSI_LCD
I can make pcb for this version norns.

Thanks on your work!

**Comment by miotislucifugis** [comment]
I still fleshing this out ...I may add schematics for the codec I built, but it is essentially just 2 modules from aliexpress and I2S wiring diagrams for RPi arent to difficult to find. Also, one could use some shield type of codec, with a pin header, and fits directly onto the GPIOs.  The point of this cheat sheet is to gather up all the info that I really had to dig for and isnt easily found anywhere else in a concise presentation, to be adapted for a range of hardware.       I have no plans to create a custom fork nor make pcbs...   norns shield is open source and the gerbers can be found in monome's  norns shield github repository.
